### ISSUE TITLE
Pull Version from pom.xml

### ISSUE THREAD

**Issue by graywolf336** [thomasf/drone-mvn#2]
Is there anyway to pull the version from the `pom.xml` file? Or what would you recommend for this?

**Comment by thomasf** [comment]
Not really.

I wrote this plugin to publish artifacts to maven repositories from non java/maven builds. If you are using maven in the first place can't you just let maven do the complete cycle in your build step instead?

**Comment by graywolf336** [comment]
Okay thanks.

That's how we started off trying, but I couldn't find a way to get it working with a password protected repository as I couldn't find a way to create the `settings.xml` with the usernames and passwords. You have any tips on doing that?

**Comment by thomasf** [comment]
IIRC, the only way I found how to do provide maven with credentials was to generate a settings.xml. 

It wouldn't be that much work supporting running any maven command in this plugin but unfortunately I don't have time to implement it right now..

You could maybe use a bash script which wraps the maven invocation and creates the settings.xml before maven is launched during the build step.. This solution does "leak" the credentials early on in the build process so you might want to be careful depending on how public the project is.

The wrapper could maybe look something like this where the M2_PASSWORD is injected in to the builder environment via drone secrets.

``` sh
#!/bin/bash

echo cat << EOF > $HOME/.m2/settings.xml
<settings>
... $M2_PASSWORD ...
</settings>
EOF

mvn ${@}

```

**Comment by graywolf336** [comment]
I will have to try that out, thanks!
